In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
device = 'mps' if torch.backends.mps.is_available() else 'cpu'

In [11]:
x = torch.tensor([-0.05, 0.05, 1], dtype=torch.float32)
# ReLU: Anything below 0 becomes 0, anything above remains the same
relu = F.relu(x)
print(relu)
sigmoid = F.sigmoid(x)
print(sigmoid)
tanh = F.tanh(x)
print(tanh)

tensor([0.0000, 0.0500, 1.0000])
tensor([0.4875, 0.5125, 0.7311])
tensor([-0.0500,  0.0500,  0.7616])


NameError: name 'exp' is not defined