In [15]:
import torch

In [6]:
randint = torch.randint(-100, 100, (6,)) # Creates tensor with random numbers within range and has a length of 6
print(randint)

tensor([ -1,  63, -79, -76, -16,  92])


In [7]:
tensor = torch.tensor([[0.1, 1.2], [2.4,3.3]])
tensor

tensor([[0.1000, 1.2000],
        [2.4000, 3.3000]])

In [8]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
torch.linspace(3, 10, steps = 5) # Go from 3 to 10 over 5 steps

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])