In [2]:
import torch
import numpy as np
import time
device = 'mps' if torch.backends.mps.is_available() else 'cpu'

In [3]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.8f}")

Elapsed time: 0.00685120


In [4]:
%%time
# Init rands for gpu and cpu
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# GPU test
start_time = time.time()

rand = torch_rand1 @ torch_rand2

end_time = time.time()

elapsed_time = end_time - start_time
print(f"GPU: {elapsed_time:.8f}")

# CPU test
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"CPU: {elapsed_time:.8f}")

GPU: 0.58735514
CPU: 0.28589272
CPU times: user 2.17 s, sys: 811 ms, total: 2.98 s
Wall time: 3.23 s


In [5]:
# Probability tensor
probabilities = torch.tensor([0.1, 0.9]) # 10% -> 0 and 90% -> 1
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [6]:
torch.tril(torch.ones(5, 5)) # Triangle lower

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
torch.triu(torch.ones(5,5)) # Triangle upper

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
# Whatever hits the condition will be filled up with second argument of masked fill
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float("-inf"))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out) # Exponent of it all

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2) # Swap the "first" dimension (2) with the third dimension (4)
out.shape

torch.Size([4, 3, 2])

In [11]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
# Stack tensors along new dimension
stacked_tensor = torch.stack([tensor1, tensor2])
print(stacked_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 0.5121, -2.1811, -0.3813], grad_fn=<SqueezeBackward4>)


In [13]:
import torch.nn.functional as F

sample_tensor = torch.tensor([1., 2., 3.])

softmax_output = F.softmax(sample_tensor, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [15]:
# Suppose we have 10 words in our 'vocabulary', and we want to embed them into 5-dimensional space.
vocab_size = 10
embed_dim = 5

# Create an embedding object
embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embed_dim)

# Example indices representing words in our vocabulary
word_indices = torch.tensor([1, 2, 8, 6], dtype=torch.long)

# Get the embeddings for these words
embedded_output = embedding(word_indices)

print(embedded_output.shape)


torch.Size([4, 5])


In [16]:
# This is like saying, "Hey computer, we have 10 different words."
vocab_size = 10

# This is like saying, "Turn each word into a sticker with 5 different spots on it."
embed_dim = 5

# This is our magical sticker machine. It knows how to turn words into stickers.
embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embed_dim)

# These are the numbers for some words we want to turn into stickers.
word_numbers = [1, 2, 8, 6]

# This tells the machine to do its magic and give us the stickers.
stickers = embedding(torch.tensor(word_numbers))

# Now we can look at our stickers!
print(stickers)


tensor([[ 0.0657,  0.4454, -0.2327,  0.0396,  0.1267],
        [-1.7355,  0.9334,  0.5152,  0.2259, -0.8137],
        [ 0.5708,  0.9402,  0.1450, -1.2770,  0.0062],
        [ 0.9000,  1.0809,  0.7363, -0.7177, -0.0598]],
       grad_fn=<EmbeddingBackward0>)
